export type FluidSimulationConfigProps = {
  SIM_RESOLUTION?: number;
  DYE_RESOLUTION?: number;
  CAPTURE_RESOLUTION?: number;
  DENSITY_DISSIPATION?: number;
  VELOCITY_DISSIPATION?: number;
  PRESSURE?: number;
  PRESSURE_ITERATIONS?: number;
  CURL?: number;
  INITIAL?: boolean;
  SPLAT_AMOUNT?: number;
  SPLAT_RADIUS?: number;
  SPLAT_FORCE?: number;
  SPLAT_KEY?: string;
  SHADING?: boolean;
  COLORFUL?: boolean;
  COLOR_UPDATE_SPEED?: number;
  COLOR_PALETTE?: string[];
  PAUSED?: boolean;
  HOVER?: boolean;
  BACK_COLOR?: string;
  TRANSPARENT?: boolean;
  BRIGHTNESS?: number;
  BLOOM?: boolean;
  BLOOM_ITERATIONS?: number;
  BLOOM_RESOLUTION?: number;
  BLOOM_INTENSITY?: number;
  BLOOM_THRESHOLD?: number;
  BLOOM_SOFT_KNEE?: number;
  SUNRAYS?: boolean;
  SUNRAYS_RESOLUTION?: number;
  SUNRAYS_WEIGHT?: number;
};

export const activeConfig = {
  SIM_RESOLUTION: 128,
  DYE_RESOLUTION: 1024,
  CAPTURE_RESOLUTION: 512,
  DENSITY_DISSIPATION: 1,
  VELOCITY_DISSIPATION: 0.2,
  PRESSURE: 0.8,
  PRESSURE_ITERATIONS: 20,
  CURL: 30,
  INITIAL: true,
  SPLAT_AMOUNT: 5,
  SPLAT_RADIUS: 0.25,
  SPLAT_FORCE: 6000,
  SPLAT_KEY: "Space",
  SHADING: true,
  COLORFUL: true,
  COLOR_UPDATE_SPEED: 10,
  COLOR_PALETTE: [],
  HOVER: true,
  BACK_COLOR: "#000000",
  TRANSPARENT: false,
  BRIGHTNESS: 0.5,
  BLOOM: true,
  BLOOM_ITERATIONS: 8,
  BLOOM_RESOLUTION: 256,
  BLOOM_INTENSITY: 0.8,
  BLOOM_THRESHOLD: 0.6,
  BLOOM_SOFT_KNEE: 0.7,
  SUNRAYS: true,
  SUNRAYS_RESOLUTION: 196,
  SUNRAYS_WEIGHT: 1.0,
};
